name: Weekly Netlify Rebuild
on:
  schedule:
    # This cron schedule runs at 00:00 UTC every Sunday (0).
    - cron: '0 0 * * 0'
  
  # This line allows you to manually trigger the action from the GitHub interface
  workflow_dispatch: 

jobs:
  rebuild:
    name: Trigger Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Ping Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}